### ISSUE TITLE
Starship cargo varient

### ISSUE THREAD

**Issue by xdthegreat** [damonvv/TundraExploration#14]
A simple part with probe cores and an opening fairing to deploy cargo. This is just a suggestion, dont take it too hard.
Link: https://cdn.teslarati.com/wp-content/uploads/2017/09/cargo-BFR-and-fairing-SpaceX.jpg

**Comment by xdthegreat** [comment]
I dont know if i should leave request for new parts here. Sorry for any inconvienience caused.

**Comment by damonvv** [comment]
This is planned, just waiting on Elon to show new pics of starship!

**Comment by nabudahab** [comment]
> This is planned, just waiting on Elon to show new pics of starship!

NASA Goddard released this image: https://pbs.twimg.com/media/D33ua_sW4AIqGpP.jpg
Dunno if it's accurate, but that's the closest you'll be able to get.

**Comment by damonvv** [comment]
@nabudahab Yeah I saw that one. Will make one based on that!

**Comment by damonvv** [comment]
@nabudahab Cargo variant coming in TE 1.7 (Already in repo)
