### ISSUE TITLE
Typo in GOJIRAII parts

### ISSUE THREAD

**Issue by FoxRomeo** [damonvv/TundraExploration#17]
In my installation parts of the GojiraII are missing (Fins) when the tech node is active that should include them.
I could pinpoint it to a typo in GameData/TundraExploration/Part/GOJIRAII
TE_18_BFS_TAIL_WING_L.cfg
TE_18_BFS_TAIL_WING_R.cfg
TE_18_BFS_TAIL.cfg
TE_18_BFS_Forward_FIN_L.cfg
TE_18_BFS_Forward_FIN_R.cfg

TechRequired = advMetalWorks
must be 
TechRequired = advMetalworks

(In Falco1/TE_F1_Interstage.cfg it's correct)

**Comment by damonvv** [comment]
Fixed
