### ISSUE TITLE
Extra_MethaloxEngine.cfg shouldnt be loaded if RealFuels/RFStockalike is installed.

### ISSUE THREAD

**Issue by ValiZockt** [damonvv/TundraExploration#26]
As soon as you have JNSQ (with RationalResources) installed all Patches in Extra_MethaloxEngine.cfg are getting applied, which is a problem if you running RFStockalike. Now all Engines affected by this patch are having two fuel mixtures (TE Methalox Patch and the RFStockalike TundraExploration Config) 

Changing all :NEEDS attributes from `:NEEDS[CryoTanksMethalox|RationalResources]` to `:NEEDS[CryoTanksMethalox|RationalResources,!RealFuels_StockEngines]` would solve that problem

`!RealFuels` instead of `!RealFuels_StockEngines` would work too

**Comment by ValiZockt** [comment]
Okay little side note, this isn't a big of a issue as i first thought, i wasn't familiar with KerbalActuators and didn't knew that all other Engine Configs (All Engines Running, Center One only, etc...) are showed in the Part Info as other Fuel Configs, while i didn't changed them in the RFStockalike TE Config there were still marked as LiquidFuel & Oxidizer and with so changed to LqdMethane with that Patch.

**Comment by JadeOfMaar** [comment]
So just add `!RealFuels` to the NEEDS? I'll go with that as you suggested it. I maintain the compatibility configs bundled in Tundra Exploration.

**Comment by ValiZockt** [comment]
Yes, just tested it again with the master to be 100% sure, works as it should.
