### ISSUE TITLE
Rodan Reaction Wheel

### ISSUE THREAD

**Issue by SofieBrink** [damonvv/TundraExploration#32]
The Rodan Cargo has very low Torque number compared to the Rodan crew

https://imgur.com/a/daslb9B

**Comment by SofieBrink** [comment]
Seems to just be missing a zero really now i look at it

**Comment by damonvv** [comment]
It should be lower, otherwise why even have RCS. 20 is just waaay to much. I will update the other pods. If 2 is too low, I can always move it up a bit.

**Comment by damonvv** [comment]
Moved it to 4.
