### ISSUE TITLE
Fuel Tanks Issue

### ISSUE THREAD

**Issue by janderglankmk** [damonvv/TundraExploration#38]
The tanks dont show the fuel they have unless you intentionally change it in the code line.

The issue is that the .cfg file does not have the Resource line 

PART
{
	name = TE_19_F9_Fairing
	module = Part
	author = Damon

	MODEL
	{
		model = TundraExploration/Parts/Ghidorah9/TE_19_F9_Fairing
	}
    rescaleFactor = 1
	
	node_stack_bottom = 0.0, 3.5, 0.43, 0.0, -1.0, 0.0, 2
	CoMOffset = 0.0, 0.0, 0.0
	TechRequired = advConstruction
	entryCost = 9000
	cost = 2000
	category = Payload
	subcategory = 0
	title = G-01 Fairing Half
	manufacturer = Tundra Exploration
	description = Fairings are designed to keep your spacecraft safe during launch... Atleast they say they do...
	tags = cck-tundra Ghidorah falcon fairing
	attachRules = 1,0,1,1,0
	mass = 0.2
	dragModelType = default
	maximum_drag = 0.2
	minimum_drag = 0.2
	angularDrag = 1
	crashTolerance = 6
	breakingForce = 1000
	breakingTorque = 1000
	maxTemp = 3600
	bulkheadProfiles = size3
	stagingIcon = DECOUPLER_HOR
	autoStrutMode = Grandparent
	
	MODULE
	{
		name = ModuleColorChanger
		shaderProperty = _EmissiveColor
		animState = false
		toggleInEditor = false
		toggleInFlight = false
		toggleAction = false
		redCurve
		{
			key = 0 0
			key = 1 0
		}
		greenCurve
		{
			key = 0 0
			key = 1 0
		}
		blueCurve
		{
			key = 0 0
			key = 1 0
		}
		alphaCurve
		{
			key = 0 0
			key = 1 0
		}
	}
	MODULE
	{
		name = ModuleB9PartSwitch
		moduleID = blockSwitch
		affectDragCubes = false
    
		SUBTYPE
		{
			name = Fairing1
			title = Fairing no TPA
			transform = Fairing_Exterior_1
		}
		SUBTYPE
		{
			name = Fairing2
			title = Fairing with TPA
			transform = Fairing_Exterior_2
			primaryColor = White
			secondaryColor = White
		}
	}
	MODULE
	{
		name = ModuleCargoBay
		DeployModuleIndex = 0
		closedPosition = 0
		lookupRadius = 3
		lookupCenter = 0, -1.9, -1
		partTypeName = Fairing
	}
	MODULE
	{
		name = ModuleCargoBay
		DeployModuleIndex = 0
		closedPosition = 0
		lookupRadius = 2.5
		lookupCenter = 0, 2.4, -1
		partTypeName = Fairing
	}
	
	DRAG_CUBE
	{
		cube = Default, 3.145,0.6655,1.355, 3.145,0.6655,1.355, 3.852,0.5859,1.976, 3.852,0.9212,0.3712, 3.145,0.6668,1.355, 3.145,0.6642,1.355, 0,0.9177,-1.094E-07, 2.5,2.358,2.5
	}
	
	MODULE
	{
		name = ModuleDecouple
		ejectionForce = 500
		explosiveNodeID = bottom
	}
	MODULE
	{
		name = FlagDecal
		textureQuadName = Decal
	}
}

**Comment by damonvv** [comment]
You can find it [here].(https://github.com/damonvv/TundraExploration/blob/master/GameData/TundraExploration/Patches/Extra_ResourceDefaults.cfg):
