### ISSUE TITLE
Possible Center Of mass Issue on Crew Dragon!

### ISSUE THREAD

**Issue by ExtincDev** [damonvv/TundraExploration#41]
Crew dragon looks to lose aerodynamic control during descent. Causing to lose control before splash down and when re-entering 

![](https://cdn.discordapp.com/attachments/544122900165165107/817189347552002068/unknown.png)

![](https://cdn.discordapp.com/attachments/544122900165165107/817189631861719100/unknown.png)

**Comment by damonvv** [comment]
Chute issue.
