### ISSUE TITLE
Add Grasshopper and F9R Nosecones as well as Grasshopper legs

### ISSUE THREAD

**Issue by abbyisnthere** [damonvv/TundraExploration#60]
After getting asked by a few friends if this was a feature in Tundra, I've decided to toss in this feature request. It's a kind of niche want but I know of quite a few people who want it so please consider!!!

![image](https://user-images.githubusercontent.com/53389189/124801673-b72a1980-df1c-11eb-92fa-d546fbe71c6a.png)

**Comment by 1Wyatt1** [comment]
I like that idea, would add some extra fun to the mod

**Comment by truehunterethan** [comment]
i like this idea too! the landing legs look so fun to play around with.

**Comment by IsaQuest** [comment]
no just leave damon alone he is already doing a lot
