### ISSUE TITLE
Engine Toggle Action Not available in official release  

### ISSUE THREAD

**Issue by TheKerbalGamer** [damonvv/TundraExploration#61]

**Comment by ValiZockt** [comment]
Well yes of course it isn't, the PR (#56) for that was after the v5.0 release. See commit 97f771f809826880c1bc0ec0020696fd7d3ff673. PR was merged on 18 June.

**Comment by SofieBrink** [comment]
Vali Explained that the feature is there and that its just not in the official release yet, they also said exactly when the feature was added. Your reaction makes absolutely no sense

**Comment by kochiBR** [comment]
Why add more modules to the engines ksp is already a heavy game on CPU and ram putting a new module on the engines would be stupid

**Comment by TheKerbalGamer** [comment]
> Why add more modules to the engines ksp is already a heavy game on CPU and ram putting a new module on the engines would be stupid

Cuz it is a basic feature all engines have

**Comment by damonvv** [comment]
Already in beta. Will be released soon.
